FROM ubuntu

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev vim nginx

COPY /path/to/file /path/to/container/file
RUN pip3 install -r /path/to/requirements.txt -i https://mirrors.aliyun.com/pypi/simple
WORKDIR /path/to/workdir

EXPOSE 80 8080
